version: '2'
services:
  eris:
    build: .
    container_name: eris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - <data_folder>:/root/.eris
    stdin_open: true
    tty: true
